name: CI - Next.js

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd conkist-web
          npm ci

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          cd conkist-web
          npm run build

      - name: Export static site
        run: |
          cd conkist-web
          npx next export

      - name: Upload out artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-out
          path: conkist-web/out

# added by CI generator
