name: CI - Next.js

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      - name: Ensure static export configured (no-op)
        run: |
          if [ -f next.config.js ]; then
            grep -q "output:\s*'export'" next.config.js || echo "Note: next.config.js doesn't set output: 'export' — skipping static export"
          else
            echo "No next.config.js found — skipping static export check"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build-artifacts-node-${{ matrix.node-version }}
          path: |
            out
            .next
            public

# added by CI generator
